### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by sohaha** [suntobright/vscode-sftp#6]
This plugin is very convenient.

Can debug function and code formatting function be supported.

**Comment by suntobright** [comment]
Hi, thank you for using this extension.

Some functionalities would be added in the following releases.

I've evaluated your suggestions, and I'm sorry to tell you that `Debug` is not the goal of this extension.
The extension is aimed to edit and browse files. And it would require a lot of work even if only support one kind of programming languages.

The code formatting function may be added in the following releases.

FYI, the VS Code has announced an [extension](https://code.visualstudio.com/blogs/2019/05/02/remote-development) to support cross-platform development.

Thanks
